version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api
    api:
      depends_on:
            - postgres
      image: pritichavan1902/simple_blog_api:latest
      ports: 
            - "3000:3000"
      environment:
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432

  