apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-blog-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: pritichavan1902/simple_blog_api
          ports:
            - containerPort: 3050