apiVersion: v1
kind: Service
metadata:
    name: simple-blog-api-node-port
spec:
    type: NodePort
    ports:
        - port:  3060
          targetPort: 3050
          nodePort: 31616
    selector:
        component: web
